apiVersion: virtualmachinemigrationresourcequota.kubevirt.io/v1alpha1
kind: VirtualMachineMigrationResourceQuota
metadata:
  name: my-vmmrq
  namespace: test
spec:
  additionalMigrationResources:
    requests.cpu: 500m
    requests.memory: 512Mi